#!/bin/sh

set -e

uci -q batch <<-EOI >/dev/null
set system.@system[0].hostname='n1-openwrt'
commit system

set luci.main.lang='zh_cn'
commit luci

set dhcp.lan.ignore=1
set dhcp.lan.dynamicdhcp='0'
delete dhcp.lan.ra_flags
add_list dhcp.lan.ra_flags='none'
delete dhcp.lan.dhcpv6
delete dhcp.lan.ra
delete dhcp.lan.ra_management
delete dhcp.lan.ra_default
commit dhcp

delete dropbear.@dropbear[0].Interface
commit dropbear

set network.lan.ipaddr='192.168.1.2'
set network.lan.gateway='192.168.1.1'
set network.lan.netmask='255.255.255.0'
set network.lan.dns='192.168.1.1'
delete network.lan.type
commit network

set uhttpd.main.redirect_https=0
commit uhttpd
EOI

if command -v docker 1>/dev/null 2>&1; then
    uci -q batch <<-EOI >/dev/null
set dockerd.globals.data_root='/mnt/mmcblk2p4/docker/'
# add_list dockerd.globals.registry_mirrors='https://mirror.baidubce.com/'
# add_list dockerd.globals.registry_mirrors='https://hub-mirror.c.163.com'
commit dockerd
EOI
fi

exit 0
