#!/bin/bash

_THIS_DIR=$(readlink -f "${BASH_SOURCE[0]}")
_THIS_DIR=$(dirname "${_THIS_DIR}")

if [[ -f "${_THIS_DIR}/.options" ]]; then
    V2RAY_ALTERID=$(grep -w V2RAY_ALTERID "${_THIS_DIR}/.options" | cut -d"=" -f2)
    V2RAY_PORT=$(grep -w V2RAY_PORT "${_THIS_DIR}/.options" | cut -d"=" -f2)
    V2RAY_SERVER=$(grep -w V2RAY_SERVER "${_THIS_DIR}/.options" | cut -d"=" -f2)
    V2RAY_UUID=$(grep -w V2RAY_UUID "${_THIS_DIR}/.options" | cut -d"=" -f2)
    V2RAY_MUX_CONCURRENCY=$(grep -w V2RAY_MUX_CONCURRENCY "${_THIS_DIR}/.options" | cut -d"=" -f2)

    V2RAY_MKCP_ALTERID=$(grep -w V2RAY_MKCP_ALTERID "${_THIS_DIR}/.options" | cut -d"=" -f2)
    V2RAY_MKCP_CLIENT_DOWN_CAPACITY=$(grep -w V2RAY_MKCP_CLIENT_DOWN_CAPACITY "${_THIS_DIR}/.options" | cut -d"=" -f2)
    V2RAY_MKCP_CLIENT_UP_CAPACITY=$(grep -w V2RAY_MKCP_CLIENT_UP_CAPACITY "${_THIS_DIR}/.options" | cut -d"=" -f2)
    V2RAY_MKCP_PASSWORD=$(grep -w V2RAY_MKCP_PASSWORD "${_THIS_DIR}/.options" | cut -d"=" -f2)
    V2RAY_MKCP_PORT=$(grep -w mkcp_port "${_THIS_DIR}/.options" | cut -d"=" -f2)
    V2RAY_MKCP_SERVER_DOWN_CAPACITY=$(grep -w V2RAY_MKCP_SERVER_DOWN_CAPACITY "${_THIS_DIR}/.options" | cut -d"=" -f2)
    V2RAY_MKCP_SERVER_UP_CAPACITY=$(grep -w V2RAY_MKCP_SERVER_UP_CAPACITY "${_THIS_DIR}/.options" | cut -d"=" -f2)
    V2RAY_MKCP_UUID=$(grep -w V2RAY_MKCP_UUID "${_THIS_DIR}/.options" | cut -d"=" -f2)
fi

V2RAY_ALTERID=${V2RAY_ALTERID:-$((RANDOM % 70 + 30))}
V2RAY_PORT=${V2RAY_PORT:-$((RANDOM % 10000 + 30000))}
V2RAY_UUID=${V2RAY_UUID:-$(cat /proc/sys/kernel/random/uuid)}
V2RAY_MUX_CONCURRENCY=${V2RAY_MUX_CONCURRENCY:-0}

V2RAY_MKCP_ALTERID=${V2RAY_MKCP_ALTERID:-$((RANDOM % 70 + 30))}
V2RAY_MKCP_CLIENT_DOWN_CAPACITY=${V2RAY_MKCP_CLIENT_DOWN_CAPACITY:-200}
V2RAY_MKCP_CLIENT_UP_CAPACITY=${V2RAY_MKCP_CLIENT_UP_CAPACITY:-50}
V2RAY_MKCP_PASSWORD=${V2RAY_MKCP_PASSWORD:-$(tr -cd '[:alnum:]' < /dev/urandom | fold -w20 | head -n1)}
V2RAY_MKCP_PORT=${V2RAY_MKCP_PORT:-$((RANDOM % 10000 + 30000))}
V2RAY_MKCP_SERVER_DOWN_CAPACITY=${V2RAY_MKCP_SERVER_DOWN_CAPACITY:-200}
V2RAY_MKCP_SERVER_UP_CAPACITY=${V2RAY_MKCP_SERVER_UP_CAPACITY:-200}
V2RAY_MKCP_UUID=${V2RAY_MKCP_UUID:-$(cat /proc/sys/kernel/random/uuid)}
V2RAY_MKCP_PASSWORD=""

{
    echo "V2RAY_ALTERID=${V2RAY_ALTERID}"
    echo "V2RAY_PORT=${V2RAY_PORT}"
    [[ -n ${V2RAY_SERVER} ]] && echo "V2RAY_SERVER=${V2RAY_SERVER}"
    echo "V2RAY_UUID=${V2RAY_UUID}"
    echo "V2RAY_MUX_CONCURRENCY=${V2RAY_MUX_CONCURRENCY}"

    echo "MKCP_ALTERID=${V2RAY_MKCP_ALTERID}"
    echo "MKCP_CLIENT_DOWN_CAPACITY=${V2RAY_MKCP_CLIENT_DOWN_CAPACITY}"
    echo "MKCP_CLIENT_UP_CAPACITY=${V2RAY_MKCP_CLIENT_UP_CAPACITY}"
    echo "MKCP_PASSWORD=${V2RAY_MKCP_PASSWORD}"
    echo "MKCP_PORT=${V2RAY_MKCP_PORT}"
    echo "MKCP_SERVER_DOWN_CAPACITY=${V2RAY_MKCP_SERVER_DOWN_CAPACITY}"
    echo "MKCP_SERVER_UP_CAPACITY=${V2RAY_MKCP_SERVER_UP_CAPACITY}"
    echo "MKCP_UUID=${V2RAY_MKCP_UUID}"
} | sort | tee "${_THIS_DIR}/.options"

unset -v _THIS_DIR
export V2RAY_ALTERID V2RAY_PORT V2RAY_SERVER V2RAY_UUID V2RAY_MUX_CONCURRENCY
export V2RAY_MKCP_ALTERID V2RAY_MKCP_CLIENT_DOWN_CAPACITY V2RAY_MKCP_CLIENT_UP_CAPACITY V2RAY_MKCP_PASSWORD V2RAY_MKCP_PORT V2RAY_MKCP_SERVER_DOWN_CAPACITY V2RAY_MKCP_SERVER_UP_CAPACITY V2RAY_MKCP_UUID
