version: "3"

services:
  v2ray:
    image: docker.io/teddysun/v2ray:5.0.6

    ports:
      - "${V2RAY_PORT}:${V2RAY_PORT}"
      - "${V2RAY_MKCP_PORT}:${V2RAY_MKCP_PORT}/udp"
    restart: always
    volumes:
      - "./config.json:/etc/v2ray/config.json"
