#!/bin/sh

set -e

uci -q batch <<EOI
set system.@system[0].conloglevel='5'
set system.@system[0].cronloglevel='8'
set system.@system[0].hostname='openwrt'
set system.@system[0].log_proto='udp'
set system.@system[0].log_size='64'
set system.@system[0].timezone='CST-8'
set system.@system[0].ttylogin='0'
set system.@system[0].urandom_seed='0'
set system.@system[0].zonename='Asia/Shanghai'
set system.@system[0]=system
commit system

set system.ntp=timeserver
delete system.ntp.server
add_list system.ntp.server='time1.aliyun.com'
add_list system.ntp.server='cn.pool.ntp.org'
set system.ntp.enable_server='1'
set system.ntp.interface='lan'
commit system
EOI

while uci -q delete dropbear.@dropbear[0]; do :; done
uci commit dropbear

uci -q batch <<EOI
add dropbear dropbear
set dropbear.@dropbear[-1].PasswordAuth='on'
set dropbear.@dropbear[-1].Port='22'
set dropbear.@dropbear[-1].Interface='lan'
commit dropbear
EOI

cat <<EOF | tee /etc/dropbear/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCrrRHaBXXcSCEqKCHLpm2z5EnmyaaukSN/sf6xNPMdX0jQcjr735GlTpaFJ7QG8PnmQiWT+OkrDVtXeFi6SKso3hXekASO8L69xKU48GVeUrTjvE1dnq822SMyLDDjGDN0nuhGrbzX7jX1ZssB07QXguHug+xnQXERr5yFRVKGOLbkLIY1qHvAy76/tVlQEo68b324g2TltV2L3mZtMsf5lI/465rWlCJZBqqI3kGKFV4RFpFS2wNpwTwyFkCpiI81LdAfUsS3Gx41Da2pmEGfaUubiwghlrtGHhcczMLwwktujngE499LNGiH9i+5I/gTsIz7Z2Qq3IpLaA4EFDsE16SwINJem6vvF4i5lUGy+vxqKAOBiAh/LH09YNjlGx9ZqFELaQBafExdSoX/MhJtPya+RzaG4T1O3nDdVOSMh3hikLFv5L7qTqUZMqjcGSKjzyxbHr8PO+PLheKJS2Cipp+e7Ym/HC5QQ/vkptolZHDbGugHBibiewirFOdHCOM= tom.shen@calix.com
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCbf0n/J8xFPekUKnfhKQJ+jrpqP9+v67qe0HDpQv+wsyuSjPCh5nQxXJ7wvJ3mG5K38PxZqbeeppLaK/qitOWGs1eZYDMjg8G8Y1nWFmTqWOH1M7q0JxX5PQOqo0angGLRk8wsKqSIsT4KDAzCCLudYp4RP3VqeKkYWgjb2izmFNR3jYmGNo2JPsPkaWPxSOA/5UUNyGWPT1Pkga6bCn3oEP57FASE4JHAf7KhdaEL9gysLLY1/wMl/Rs4PpJdepJ4K3B5WY7KqVqBjmTJmM6tUOzam0JEF4iwAFc3fUXynWj6BmTQD+ERPykr9W72S/o6PdgLd1BKDiXZ/p4tx4h3 tshen@remote
EOF

sed -i -e 's|https://downloads.openwrt.org|http://mirrors.ustc.edu.cn/openwrt|g' -e 's|http://downloads.openwrt.org|http://mirrors.ustc.edu.cn/openwrt|g' /etc/opkg/distfeeds.conf
# sed -i -e 's|http://mirrors.ustc.edu.cn/openwrt|http://downloads.openwrt.org|g' /etc/opkg/distfeeds.conf

if ! grep -s -q "net.ipv4.tcp_fastopen=3" /etc/sysctl.conf; then
    echo "net.ipv4.tcp_fastopen=3" | tee -a /etc/sysctl.conf
fi

# The following is only work for x86 openwrt
if [ -f /boot/grub/grub.cfg ]; then
    sed -i -e 's/set timeout="5"/set timeout="1"/g' /boot/grub/grub.cfg
fi

exit 0
