#!/bin/sh

set -e

uci -q batch <<-EOI >/dev/null
set system.@system[0].hostname='x86-64'
commit system

set luci.main.lang='zh_cn'
commit luci

set dhcp.lan.ignore=1
set dhcp.lan.dynamicdhcp='0'
delete dhcp.lan.ra_flags
add_list dhcp.lan.ra_flags='none'
delete dhcp.lan.dhcpv6
delete dhcp.lan.ra
delete dhcp.lan.ra_management
delete dhcp.lan.ra_default
commit dhcp

set network.lan.ipaddr='192.168.1.5'
set network.lan.gateway='192.168.1.1'
set network.lan.netmask='255.255.255.0'
set network.lan.dns='192.168.1.1'
delete network.lan.type
commit network
EOI

exit 0
