version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:v4.44.0
    ports:
      - 1080:1080
      - 1081:1081
    restart: always
    volumes:
      - "./config.json:/etc/v2ray/config.json"

  v2ray-mkcp:
    image: v2fly/v2fly-core:v4.44.0
    ports:
      - 1090:1090
      - 1091:1091
    restart: always
    volumes:
      - "./config-mkcp.json:/etc/v2ray/config.json"
