#!/bin/sh

set -e

uci -q batch <<-EOI >/dev/null
set system.@system[0].hostname='newifi-d2'
commit system

set dhcp.lan.force='1'
commit system

set firewall.defaults.flow_offloading='1'
set firewall.defaults.flow_offloading_hw='1'
commit firewall

set uhttpd.main.redirect_https=1
commit uhttpd
EOI

exit 0
